#!/usr/bin/env python

Import("env")
Import("env_modules")

env_spout = env_modules.Clone();

env_spout.add_source_files(env.modules_sources, "*.cpp")

env.Append(LIBS=File("#thirdparty/spout-library/Binaries/x64/SpoutLibrary.lib"))
